version: "3"
services:
  client:
    stdin_open: true
    build:
      context: ./web
      dockerfile: ./Dockerfile.fe
    environment:
      - HOST=0.0.0.0
      - PORT=8080
    ports:
      - "8080:8080"
    volumes:
      - "./web:/app"
      - exclude:/app/node_modules/
  web:
    build: .
    ports:
    - "5000:5000"
    depends_on:
      - redis
    volumes:
    - type: bind
      target: /usr/src/app/data
      source: ${UPLOAD_FOLDER}
  redis:
    image: "redis:alpine"
    expose:
      - "6379"
  dashboard:
    build: ./dashboard
    ports:
    - "9181:9181"
    depends_on:
      - redis
    environment:
      - RQ_DASHBOARD_REDIS_URL=redis://redis:6379
      - RQ_DASHBOARD_USERNAME=${RQ_DASHBOARD_USERNAME}
      - RQ_DASHBOARD_PASSWORD=${RQ_DASHBOARD_PASSWORD}
  worker:
    build: .
    depends_on:
      - redis
    volumes:
    - type: bind
      target: /usr/src/app/data
      source: ${UPLOAD_FOLDER}
    command: sh -c "pipenv run rqworker -u redis://redis:6379"
volumes:
  exclude: