version: "3"
services:
  web:
    build: .
    ports:
    - "5000:5000"
    depends_on:
      - redis
    volumes:
    - type: bind
      target: /usr/src/app/data
      source: ${UPLOAD_FOLDER}
  redis:
    image: "redis:alpine"
    expose:
      - "6379"
  dashboard:
    build: ./dashboard
    ports:
    - "9181:9181"
    depends_on:
      - redis
    environment:
      - RQ_DASHBOARD_REDIS_URL=redis://redis:6379
      - RQ_DASHBOARD_USERNAME=${RQ_DASHBOARD_USERNAME}
      - RQ_DASHBOARD_PASSWORD=${RQ_DASHBOARD_PASSWORD}
  worker:
    build: .
    depends_on:
      - redis
    volumes:
    - type: bind
      target: /usr/src/app/data
      source: ${UPLOAD_FOLDER}
    command: sh -c "nvcc --version && pipenv run rqworker -u redis://redis:6379"
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: [gpu]