version: "3"
services:
  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile.fe
    depends_on:
      - web
    ports:
      - "80:80"
  web:
    build: .
    depends_on:
      - redis
    expose:
      - "5000"
    volumes:
    - type: bind
      target: /usr/src/app/data
      source: ${UPLOAD_FOLDER}
  redis:
    image: "redis:alpine"
  dashboard:
    build: ./dashboard
    depends_on:
      - redis
    environment:
      - RQ_DASHBOARD_REDIS_URL=redis://redis:6379
      - RQ_DASHBOARD_USERNAME=${RQ_DASHBOARD_USERNAME}
      - RQ_DASHBOARD_PASSWORD=${RQ_DASHBOARD_PASSWORD}
  worker:
    build: .
    depends_on:
      - redis
    volumes:
    - type: bind
      target: /usr/src/app/data
      source: ${UPLOAD_FOLDER}
    command: sh -c "pipenv run rqworker --exception-handler 'images_to_mesh.app.exception_handlers.exeption_handlers.queue_handler' --with-scheduler -u redis://redis:6379"