# workaround until this is released: https://github.com/webpack/webpack/pull/14584
#FROM node:16.13-alpine3.12
FROM node:16.14.2-alpine3.14

WORKDIR /app

COPY . /app

RUN yarn install

CMD ["yarn", "run", "start"]
