FROM node:alpine
WORKDIR /app
COPY ./package.json /app
RUN yarn install
COPY . /app
RUN yarn build

FROM nginx:alpine
COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=0 /app/build/. /usr/share/nginx/html/