# workaround until this is released: https://github.com/webpack/webpack/pull/14584
FROM node:16.13-alpine3.12

WORKDIR /app

COPY ./package.json /app

RUN yarn install

COPY . /app

CMD ["yarn", "run", "start"]
